name: dart_flight
version: 0.1.0
description: >-
  dart_flight is a lightweight application framework for the Dart language that
  enables rapid development and deployment of servers utilizing the MVC
  (or Model-View-Controller) architectural pattern to handle requests.

# homepage:
repository: https://github.com/dartFlight/dart_flight
issue_tracker: https://github.com/dartFlight/dart_flight_issues
# documentation:

environment:
  sdk: '^3.0.0'

dependencies:
  dotenv: ^4.2.0
  yaml: ^3.1.2
  #

dev_dependencies:
  #

# executables:
  #

# platforms:
  #

publish_to: none

# funding:
  #
